### ISSUE TITLE
About data preprocessing

### ISSUE THREAD

**Issue by JuweiChan** [yuanenming/mb-str#7]
Hi Yuan, sorry to bother. I wonder if users and items with too few interactions were filtered out after preprocessing, if so, could you tell me the rules? i.e. Is there a requirement for session length during data preprocessing, and will sessions shorter than a certain length be deleted?

**Comment by yuanenming** [comment]
Hi Juwei, Thanks for your attention. 

Yes, it is important to preprocess the raw interaction data. Because the interaction data are essentially long-tail distributed, which means there may be a lot of items of users with only few interactions. Actually, if you want to adapt MB-STR to your own datasets, you can customize your own data preprocessing pipeline. Here, in our experiments, we use the preprocessed datasets released by previous works.

"We use the same pre-processed datasets with MB-GMN. As the time information of the original used Beibei dataset in [40] is not available, we use the same pre-processed Yelp dataset from MATN [39] as an alternative"

To be more concrete, the data preprocess pipeline we used is as follows:
1. There are three times of filtering, to avoid picked users/items with few connections due to a previous filtering process.
2. In the first time, users and items that have <= 20 overall interactions or <2 target interactions are filtered out.
3. In the second time, users and items that have <= 10 overall interactions or <2 target interactions are filtered out.
4. In the last time, items are not filtered, users that have <= 5 overall interactions or <2 target interactions are filtered out.

Hope this can help you.

**Comment by JuweiChan** [comment]
> Hi Juwei, Thanks for your attention.
> 
> Yes, it is important to preprocess the raw interaction data. Because the interaction data are essentially long-tail distributed, which means there may be a lot of items of users with only few interactions. Actually, if you want to adapt MB-STR to your own datasets, you can customize your own data preprocessing pipeline. Here, in our experiments, we use the preprocessed datasets released by previous works.
> 
> "We use the same pre-processed datasets with MB-GMN. As the time information of the original used Beibei dataset in [40] is not available, we use the same pre-processed Yelp dataset from MATN [39] as an alternative"
> 
> To be more concrete, the data preprocess pipeline we used is as follows:
> 
> 1. There are three times of filtering, to avoid picked users/items with few connections due to a previous filtering process.
> 2. In the first time, users and items that have <= 20 overall interactions or <2 target interactions are filtered out.
> 3. In the second time, users and items that have <= 10 overall interactions or <2 target interactions are filtered out.
> 4. In the last time, items are not filtered, users that have <= 5 overall interactions or <2 target interactions are filtered out.
> 
> Hope this can help you.

Thank you so much!
